# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft_types.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'raft_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10raft_types.proto\x12\x04raft\"J\n\x0cLogOperation\x12\x0f\n\x07op_type\x18\x01 \x01(\r\x12\r\n\x05\x66lags\x18\x02 \x01(\x04\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x0c\"1\n\x07LogData\x12&\n\noperations\x18\x01 \x03(\x0b\x32\x12.raft.LogOperation\")\n\nIndexValue\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\r\n\x05index\x18\x02 \x01(\x04\"7\n\x06Server\x12\x10\n\x08suffrage\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"B\n\x12\x43onfigurationValue\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x1d\n\x07servers\x18\x02 \x03(\x0b\x32\x0c.raft.Server\"0\n\x14LocalNodeConfigValue\x12\x18\n\x10\x64\x65sired_suffrage\x18\x01 \x01(\tB*Z(github.com/openbao/openbao/physical/raftb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/openbao/openbao/physical/raft'
  _globals['_LOGOPERATION']._serialized_start=26
  _globals['_LOGOPERATION']._serialized_end=100
  _globals['_LOGDATA']._serialized_start=102
  _globals['_LOGDATA']._serialized_end=151
  _globals['_INDEXVALUE']._serialized_start=153
  _globals['_INDEXVALUE']._serialized_end=194
  _globals['_SERVER']._serialized_start=196
  _globals['_SERVER']._serialized_end=251
  _globals['_CONFIGURATIONVALUE']._serialized_start=253
  _globals['_CONFIGURATIONVALUE']._serialized_end=319
  _globals['_LOCALNODECONFIGVALUE']._serialized_start=321
  _globals['_LOCALNODECONFIGVALUE']._serialized_end=369
# @@protoc_insertion_point(module_scope)
