# credits: https://github.com/YouMightNotNeedKubernetes/etcd
# label each node with `docker node update --label-add vault=true NODE-ID`
# create config with `docker config create --template-driver golang vault-node-config-hcl config.hcl`
# TODO: fix /data permissions to openbao:openbao (100:1000)
x-deploy: &x-default-deploy
  replicas: ${VAULT_REPLICAS:-3}
  placement:
    max_replicas_per_node: 1
    constraints:
      - node.role == manager
      - node.labels.vault == true
    preferences:
      - spread: node.labels.vault
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
  rollback_config:
    parallelism: 1
    delay: 5s
    failure_action: pause
    monitor: 60s
    max_failure_ratio: 0.3
  update_config:
    parallelism: 1
    delay: 5s
    failure_action: rollback
    monitor: 60s
    max_failure_ratio: 0.3
    order: stop-first
  resources:
    limits:
      cpus: '0.50'
      memory: 512M
    reservations:
      cpus: '0.25'
      memory: 256M

x-logging: &x-default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

networks:
  vault_lan:
    name: vault_lan
    external: true

volumes:
  vault:
    external: true

configs:
  vault-config-hcl:
    file: ./config.hcl
    template_driver: golang

services:
  vault:
    image: openbao/openbao
    hostname: bao-{{.Task.Slot}}
    configs:
      - source: vault-config-hcl
        target: /openbao/config/vault.hcl
        uid: '0'
        gid: '0'
        mode: 0444
    environment:
      - BAO_CLUSTER_INTERFACE=eth0
      - BAO_LOG_LEVEL=info
      - VAULT_ADDR=http://127.0.0.1:8200
    command: ["server"]
    ports:
      - 8200:8200
    networks:
      - vault_lan
    volumes:
      - vault:/data
    deploy: *x-default-deploy
    logging: *x-default-logging